[root@pln-petipareplica ~]#
[root@pln-petipareplica ~]# rpm -qa | grep -E "ipa-server|389-ds-base|pki-" | sort
389-ds-base-1.4.3.39-3.module+el8.10.0+21535+f663b039.x86_64
389-ds-base-libs-1.4.3.39-3.module+el8.10.0+21535+f663b039.x86_64
idm-pki-acme-10.15.0-1.module+el8.10.0+21280+cce842b8.noarch
idm-pki-base-10.15.0-1.module+el8.10.0+21280+cce842b8.noarch
idm-pki-base-java-10.15.0-1.module+el8.10.0+21280+cce842b8.noarch
idm-pki-ca-10.15.0-1.module+el8.10.0+21280+cce842b8.noarch
idm-pki-kra-10.15.0-1.module+el8.10.0+21280+cce842b8.noarch
idm-pki-server-10.15.0-1.module+el8.10.0+21280+cce842b8.noarch
idm-pki-symkey-10.15.0-1.module+el8.10.0+21280+cce842b8.x86_64
idm-pki-tools-10.15.0-1.module+el8.10.0+21280+cce842b8.x86_64
ipa-server-4.9.13-8.module+el8.10.0+21432+ee17c097.x86_64
ipa-server-common-4.9.13-8.module+el8.10.0+21432+ee17c097.noarch
ipa-server-dns-4.9.13-8.module+el8.10.0+21432+ee17c097.noarch
python3-idm-pki-10.15.0-1.module+el8.10.0+21280+cce842b8.noarch
[root@pln-petipareplica ~]#
[root@pln-petipareplica ~]#
[root@pln-petipareplica ~]# ls /etc/dirsrv/ 2>/dev/null
config  schema
[root@pln-petipareplica ~]# ls /var/lib/ipa/sysrestore/ 2>/dev/null
[root@pln-petipareplica ~]# sudo systemctl is-active dirsrv@IPA-CALIX-LOCAL 2>&1
inactive
[root@pln-petipareplica ~]# hostname -f
pln-petipareplica.ipa.calix.local
[root@pln-petipareplica ~]# cat /etc/resolv.conf
# Generated by NetworkManager
search ipa.calix.local
nameserver 10.172.248.31
[root@pln-petipareplica ~]# ipa host-show pln-petipareplica.ipa.calix.local 2>&1
IPA client is not configured on this system
[root@pln-petipareplica ~]# exidig @172.23.49.10 -x <pln-petipareplica IP> +short
-bash: pln-petipareplica: No such file or directory
[root@pln-petipareplica ~]# dig @172.23.49.10 -x <pln-petipareplica IP> +short
-bash: pln-petipareplica: No such file or directory
[root@pln-petipareplica ~]#
[root@pln-petipareplica ~]#
[root@pln-petipareplica ~]#
[root@pln-petipareplica ~]# dig @172.23.49.10 -x <pln-petipareplica IP> +short
-bash: pln-petipareplica: No such file or directory
[root@pln-petipareplica ~]# hostname -I
10.172.248.57 192.168.122.1
[root@pln-petipareplica ~]# dig @172.23.49.10 -x 10.172.248.57 +short
[root@pln-petipareplica ~]#
[root@pln-petipareplica ~]#
[root@pln-petipareplica ~]# dig @172.23.49.10 pln-petipareplica.ipa.calix.local +short
[root@pln-petipareplica ~]#

[root@cpeg-ipareplica ~]# kinit hsuma
Password for hsuma@IPA.CALIX.LOCAL:
[root@cpeg-ipareplica ~]# ipa host-show pln-petipareplica.ipa.calix.local 2>&1
ipa: ERROR: pln-petipareplica.ipa.calix.local: host not found
[root@cpeg-ipareplica ~]# ipa-replica-manage list
sjc-ipareplica01.ipa.calix.local: master
nan-ipareplica01.ipa.calix.local: master
ric-ipareplica01.ipa.calix.local: master
ric-ipareplica.ipa.calix.local: master
cpeg-ipareplica.ipa.calix.local: master
[root@cpeg-ipareplica ~]# dig @172.23.49.10 pln-petipareplica.ipa.calix.local +short
[root@cpeg-ipareplica ~]# dig @172.23.49.10 -x <pln-petipareplica IP> +short
-bash: pln-petipareplica: No such file or directory
[root@cpeg-ipareplica ~]#
[root@cpeg-ipareplica ~]# dig @172.23.49.10 -x 10.172.248.57 +short
[root@cpeg-ipareplica ~]#
[root@cpeg-ipareplica ~]#
[root@cpeg-ipareplica ~]#
