~
~
~
~
~
Feb 26 21:57:48 ocp-ai-gpu01.calix.local systemd[1]: Starting Ensure NM resolv.conf has DNS servers (OVN-K bare-metal fix)...
Feb 26 21:57:48 ocp-ai-gpu01.calix.local ensure-nm-dns.sh[3782]: [ensure-nm-dns] Waiting for /var/run/NetworkManager/resolv.conf to exist (max 120s)...
Feb 26 21:59:48 ocp-ai-gpu01.calix.local ensure-nm-dns.sh[3782]: [ensure-nm-dns] WARN: /var/run/NetworkManager/resolv.conf not found after 120s, creating it
Feb 26 21:59:48 ocp-ai-gpu01.calix.local ensure-nm-dns.sh[3782]: [ensure-nm-dns] /var/run/NetworkManager/resolv.conf exists after 120s
Feb 26 21:59:48 ocp-ai-gpu01.calix.local ensure-nm-dns.sh[3782]: [ensure-nm-dns] No nameservers found, injecting DNS...
Feb 26 21:59:48 ocp-ai-gpu01.calix.local ensure-nm-dns.sh[3782]: [ensure-nm-dns] Injecting DNS into ovs-if-br-ex NM connection...
Feb 26 21:59:48 ocp-ai-gpu01.calix.local ensure-nm-dns.sh[3782]: [ensure-nm-dns] DNS fix applied:
Feb 26 21:59:48 ocp-ai-gpu01.calix.local ensure-nm-dns.sh[5194]: # Injected by ensure-nm-dns.sh (MachineConfig 99-worker-nm-dns-fix)
Feb 26 21:59:48 ocp-ai-gpu01.calix.local ensure-nm-dns.sh[5194]: # OVN-K does not inject DNS into ovs-if-br-ex on bare metal
Feb 26 21:59:48 ocp-ai-gpu01.calix.local ensure-nm-dns.sh[5194]: search calix.local
Feb 26 21:59:48 ocp-ai-gpu01.calix.local ensure-nm-dns.sh[5194]: nameserver 10.172.248.31
Feb 26 21:59:48 ocp-ai-gpu01.calix.local ensure-nm-dns.sh[5194]: nameserver 10.172.248.32
Feb 26 21:59:48 ocp-ai-gpu01.calix.local systemd[1]: Finished Ensure NM resolv.conf has DNS servers (OVN-K bare-metal fix).
[core@ocp-ai-gpu01 ~]$
[core@ocp-ai-gpu01 ~]$
[core@ocp-ai-gpu01 ~]$
[core@ocp-ai-gpu01 ~]$ systemctl status ensure-nm-dns.service
● ensure-nm-dns.service - Ensure NM resolv.conf has DNS servers (OVN-K bare-metal fix)
     Loaded: loaded (/etc/systemd/system/ensure-nm-dns.service; enabled; preset: disabled)
     Active: active (exited) since Thu 2026-02-26 21:59:48 UTC; 4min 2s ago
   Main PID: 3782 (code=exited, status=0/SUCCESS)
        CPU: 94ms

Feb 26 21:59:48 ocp-ai-gpu01.calix.local ensure-nm-dns.sh[3782]: [ensure-nm-dns] /var/run/NetworkManager/resolv.conf exists after 120s
Feb 26 21:59:48 ocp-ai-gpu01.calix.local ensure-nm-dns.sh[3782]: [ensure-nm-dns] No nameservers found, injecting DNS...
Feb 26 21:59:48 ocp-ai-gpu01.calix.local ensure-nm-dns.sh[3782]: [ensure-nm-dns] Injecting DNS into ovs-if-br-ex NM connection...
Feb 26 21:59:48 ocp-ai-gpu01.calix.local ensure-nm-dns.sh[3782]: [ensure-nm-dns] DNS fix applied:
Feb 26 21:59:48 ocp-ai-gpu01.calix.local ensure-nm-dns.sh[5194]: # Injected by ensure-nm-dns.sh (MachineConfig 99-worker-nm-dns-fix)
Feb 26 21:59:48 ocp-ai-gpu01.calix.local ensure-nm-dns.sh[5194]: # OVN-K does not inject DNS into ovs-if-br-ex on bare metal
Feb 26 21:59:48 ocp-ai-gpu01.calix.local ensure-nm-dns.sh[5194]: search calix.local
Feb 26 21:59:48 ocp-ai-gpu01.calix.local ensure-nm-dns.sh[5194]: nameserver 10.172.248.31
Feb 26 21:59:48 ocp-ai-gpu01.calix.local ensure-nm-dns.sh[5194]: nameserver 10.172.248.32
Feb 26 21:59:48 ocp-ai-gpu01.calix.local systemd[1]: Finished Ensure NM resolv.conf has DNS servers (OVN-K bare-metal fix).
[core@ocp-ai-gpu01 ~]$ cat /var/run/NetworkManager/resolv.conf
# Generated by NetworkManager
search calix.local
[core@ocp-ai-gpu01 ~]$




cat <<'EOF' | oc apply -f -
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-worker-nm-dns-fix
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.5.0
    storage:
      files:
        - path: /usr/local/bin/ensure-nm-dns.sh
          mode: 0755
          overwrite: true
          contents:
            source: "data:text/plain;charset=utf-8;base64,IyEvYmluL2Jhc2gKUkVTT0xWPSIvdmFyL3J1bi9OZXR3b3JrTWFuYWdlci9yZXNvbHYuY29uZiIKRE5TMT0iMTAuMTcyLjI0OC4zMSIKRE5TMj0iMTAuMTcyLjI0OC4zMiIKU0VBUkNIPSJjYWxpeC5sb2NhbCIKTUFYX1dBSVQ9MTIwCklOVEVSVkFMPTIKCmVjaG8gIltlbnN1cmUtbm0tZG5zXSBXYWl0aW5nIGZvciAke1JFU09MVn0gdG8gZXhpc3QgKG1heCAke01BWF9XQUlUfXMpLi4uIgoKZWxhcHNlZD0wCndoaWxlIFsgISAtZiAiJFJFU09MViIgXTsgZG8KICBpZiBbICRlbGFwc2VkIC1nZSAkTUFYX1dBSVQgXTsgdGhlbgogICAgZWNobyAiW2Vuc3VyZS1ubS1kbnNdIFdBUk46ICR7UkVTT0xWfSBub3QgZm91bmQgYWZ0ZXIgJHtNQVhfV0FJVH1zLCBjcmVhdGluZyBpdCIKICAgIG1rZGlyIC1wIC92YXIvcnVuL05ldHdvcmtNYW5hZ2VyCiAgICB0b3VjaCAiJFJFU09MViIKICAgIGJyZWFrCiAgZmkKICBzbGVlcCAkSU5URVJWQUwKICBlbGFwc2VkPSQoKGVsYXBzZWQgKyBJTlRFUlZBTCkpCmRvbmUKCmVjaG8gIltlbnN1cmUtbm0tZG5zXSAke1JFU09MVn0gZXhpc3RzIGFmdGVyICR7ZWxhcHNlZH1zIgoKaWYgZ3JlcCAtcSAibmFtZXNlcnZlciIgIiRSRVNPTFYiIDI+L2Rldi9udWxsOyB0aGVuCiAgZWNobyAiW2Vuc3VyZS1ubS1kbnNdIEROUyBhbHJlYWR5IHByZXNlbnQgaW4gJHtSRVNPTFZ9LCBub3RoaW5nIHRvIGRvIgogIGNhdCAiJFJFU09MViIKICBleGl0IDAKZmkKCmVjaG8gIltlbnN1cmUtbm0tZG5zXSBObyBuYW1lc2VydmVycyBmb3VuZCwgaW5qZWN0aW5nIEROUy4uLiIKcHJpbnRmICIjIEluamVjdGVkIGJ5IGVuc3VyZS1ubS1kbnMuc2ggKE1hY2hpbmVDb25maWcgOTktd29ya2VyLW5tLWRucy1maXgpXG4jIE9WTi1LIGRvZXMgbm90IGluamVjdCBETlMgaW50byBvdnMtaWYtYnItZXggb24gYmFyZSBtZXRhbFxuc2VhcmNoICVzXG5uYW1lc2VydmVyICVzXG5uYW1lc2VydmVyICVzXG4iICIkU0VBUkNIIiAiJEROUzEiICIkRE5TMiIgPiAiJFJFU09MViIKCmlmIG5tY2xpIGNvbm5lY3Rpb24gc2hvdyBvdnMtaWYtYnItZXggJj4vZGV2L251bGw7IHRoZW4KICBlY2hvICJbZW5zdXJlLW5tLWRuc10gSW5qZWN0aW5nIEROUyBpbnRvIG92cy1pZi1ici1leCBOTSBjb25uZWN0aW9uLi4uIgogIG5tY2xpIGNvbm5lY3Rpb24gbW9kaWZ5IG92cy1pZi1ici1leCBpcHY0LmRucyAiJHtETlMxfSAke0ROUzJ9IiBpcHY0LmRucy1wcmlvcml0eSA0MAogIG5tY2xpIGNvbm5lY3Rpb24gdXAgb3ZzLWlmLWJyLWV4IDI+L2Rldi9udWxsIHx8IHRydWUKZmkKCmVjaG8gIltlbnN1cmUtbm0tZG5zXSBETlMgZml4IGFwcGxpZWQ6IgpjYXQgIiRSRVNPTFYiCmV4aXQgMAo="
    systemd:
      units:
        - name: ensure-nm-dns.service
          enabled: true
          contents: |
            [Unit]
            Description=Ensure NM resolv.conf has DNS servers (OVN-K bare-metal fix)
            After=NetworkManager.service
            Before=kubelet.service
            Before=nodeip-configuration.service

            [Service]
            Type=oneshot
            RemainAfterExit=yes
            ExecStart=/usr/local/bin/ensure-nm-dns.sh
            TimeoutStartSec=180

            [Install]
            WantedBy=multi-user.target
EOF


55: /etc/kubernetes/kubelet.conf overwrite=True content=source
56: /usr/local/bin/kubenswrapper overwrite=True content=source
57: /etc/chrony.conf overwrite=True content=source
hsuma@plnx-admin:~/ocp-ai-config$

oc get mcp worker
oc logs -n openshift-machine-config-operator deployment/machine-config-controller --tail=3


        - path: /usr/local/bin/ensure-nm-dns.sh
          mode: 0755
          contents:
            inline: |
              #!/bin/bash
              # ensure-nm-dns.sh
              # Ensures /var/run/NetworkManager/resolv.conf has DNS servers
              # before kubelet starts. Fixes OVN-K bare-metal bug where
              # ovs-if-br-ex is created at runtime without DNS, causing
              # resolv-prepender.sh to hang indefinitely and kubelet to
              # fail with "NM resolv-prepender failed".
              #
              # Root cause: OVN-K creates ovs-if-br-ex in /run/NetworkManager/
              # system-connections/ (tmpfs, wiped on reboot) without ipv4.dns.
              # NM then generates resolv.conf with no nameservers.
              #
              # This runs as a oneshot before kubelet — no race condition.
              #
              # Cluster: ocp-ai.calix.local (OCP 4.20.13)
              # DNS: 10.172.248.31, 10.172.248.32
              # Author: Haj Suma
              # Date: February 26, 2026

              RESOLV="/var/run/NetworkManager/resolv.conf"
              DNS1="10.172.248.31"
              DNS2="10.172.248.32"
              SEARCH="calix.local"
              MAX_WAIT=120
              INTERVAL=2

              echo "[ensure-nm-dns] Waiting for ${RESOLV} to exist (max ${MAX_WAIT}s)..."

              elapsed=0
              while [ ! -f "$RESOLV" ]; do
                if [ $elapsed -ge $MAX_WAIT ]; then
                  echo "[ensure-nm-dns] WARN: ${RESOLV} not found after ${MAX_WAIT}s, creating it"
                  mkdir -p /var/run/NetworkManager
                  touch "$RESOLV"
                  break
                fi
                sleep $INTERVAL
                elapsed=$((elapsed + INTERVAL))
              done

              echo "[ensure-nm-dns] ${RESOLV} exists after ${elapsed}s"

              if grep -q "nameserver" "$RESOLV" 2>/dev/null; then
                echo "[ensure-nm-dns] DNS already present in ${RESOLV}, nothing to do"
                cat "$RESOLV"
                exit 0
              fi

              echo "[ensure-nm-dns] No nameservers found, injecting DNS..."
              printf "# Injected by ensure-nm-dns.sh (MachineConfig 99-worker-nm-dns-fix)\n# OVN-K does not inject DNS into ovs-if-br-ex on bare metal\nsearch %s\nnameserver %s\nnameserver %s\n" "$SEARCH" "$DNS1" "$DNS2" > "$RESOLV"

              if nmcli connection show ovs-if-br-ex &>/dev/null; then
                echo "[ensure-nm-dns] Injecting DNS into ovs-if-br-ex NM connection..."
                nmcli connection modify ovs-if-br-ex ipv4.dns "${DNS1} ${DNS2}" ipv4.dns-priority 40
                nmcli connection up ovs-if-br-ex 2>/dev/null || true
              fi

              echo "[ensure-nm-dns] DNS fix applied:"
              cat "$RESOLV"
              exit 0
    systemd:
      units:
        - name: ensure-nm-dns.service
          enabled: true
          contents: |
            [Unit]
            Description=Ensure NM resolv.conf has DNS servers (OVN-K bare-metal fix)
            After=NetworkManager.service
            Before=kubelet.service
            Before=nodeip-configuration.service

            [Service]
            Type=oneshot
            RemainAfterExit=yes
            ExecStart=/usr/local/bin/ensure-nm-dns.sh
            TimeoutStartSec=180

            [Install]
            WantedBy=multi-user.target
