hsuma@plnx-admin:~/ocp-ai-config$ oc logs -n openshift-machine-config-operator deployment/machine-config-controller --tail=5
Defaulted container "machine-config-controller" out of: machine-config-controller, kube-rbac-proxy
Report: error at $.storage.files.58.overwrite, line 1 col 190155: overwrite must be false if source is unspecified
; component errors: <nil>
I0226 21:02:17.514614       1 render_controller.go:408] Error syncing machineconfigpool worker: could not generate rendered MachineConfig: render reconciliation error: parsing new Ignition config from machineconfig "rendered-worker-20b4c0c1ca36e818ba5768405bb58263" failed: failed to parse Ignition config: parsing Ignition config spec v3 failed with error: config is not valid
Report: error at $.storage.files.58.overwrite, line 1 col 190155: overwrite must be false if source is unspecified
; component errors: <nil>
hsuma@plnx-admin:~/ocp-ai-config$
hsuma@plnx-admin:~/ocp-ai-config$
hsuma@plnx-admin:~/ocp-ai-config$ oc logs -n openshift-machine-config-operator deployment/machine-config-controller --tail=5
Defaulted container "machine-config-controller" out of: machine-config-controller, kube-rbac-proxy
Report: error at $.storage.files.58.overwrite, line 1 col 190155: overwrite must be false if source is unspecified
; component errors: <nil>
I0226 21:02:22.827173       1 render_controller.go:408] Error syncing machineconfigpool worker: could not generate rendered MachineConfig: render reconciliation error: parsing new Ignition config from machineconfig "rendered-worker-20b4c0c1ca36e818ba5768405bb58263" failed: failed to parse Ignition config: parsing Ignition config spec v3 failed with error: config is not valid
Report: error at $.storage.files.58.overwrite, line 1 col 190155: overwrite must be false if source is unspecified
; component errors: <nil>



hsuma@plnx-admin:~/ocp-ai-config$
hsuma@plnx-admin:~/ocp-ai-config$
hsuma@plnx-admin:~/ocp-ai-config$ oc get mc -A
NAME                                                GENERATEDBYCONTROLLER                      IGNITIONVERSION   AGE
00-master                                           035a7f3c16e820ed0461b25ba82c263131ff6c3d   3.5.0             10d
00-override-master-generated-crio-default-ulimits                                              3.5.0             10d
00-override-worker-generated-crio-default-ulimits                                              3.5.0             10d
00-worker                                           035a7f3c16e820ed0461b25ba82c263131ff6c3d   3.5.0             10d
01-master-container-runtime                         035a7f3c16e820ed0461b25ba82c263131ff6c3d   3.5.0             10d
01-master-kubelet                                   035a7f3c16e820ed0461b25ba82c263131ff6c3d   3.5.0             10d
01-worker-container-runtime                         035a7f3c16e820ed0461b25ba82c263131ff6c3d   3.5.0             10d
01-worker-kubelet                                   035a7f3c16e820ed0461b25ba82c263131ff6c3d   3.5.0             10d
50-master-auto-sizing-disabled                                                                 3.5.0             10d
50-masters-chrony-configuration                                                                3.1.0             10d
50-worker-auto-sizing-disabled                                                                 3.5.0             10d
50-workers-chrony-configuration                                                                3.1.0             10d
97-master-generated-kubelet                         035a7f3c16e820ed0461b25ba82c263131ff6c3d   3.5.0             10d
97-worker-generated-kubelet                         035a7f3c16e820ed0461b25ba82c263131ff6c3d   3.5.0             10d
98-master-generated-kubelet                         035a7f3c16e820ed0461b25ba82c263131ff6c3d   3.5.0             10d
98-worker-generated-kubelet                         035a7f3c16e820ed0461b25ba82c263131ff6c3d   3.5.0             10d
99-assisted-installer-master-ssh                                                               3.1.0             10d
99-master-chrony                                                                               3.2.0             7d3h
99-master-generated-registries                      035a7f3c16e820ed0461b25ba82c263131ff6c3d   3.5.0             10d
99-master-ssh                                                                                  3.2.0             10d
99-worker-chrony                                                                               3.2.0             7d3h
99-worker-generated-registries                      035a7f3c16e820ed0461b25ba82c263131ff6c3d   3.5.0             10d
99-worker-mtu-9000                                                                             3.2.0             8d
99-worker-nm-dns-fix                                                                           3.5.0             52m
99-worker-ssh                                                                                  3.2.0             10d
rendered-master-327f71483a87324f006c932d7f3a74a8    035a7f3c16e820ed0461b25ba82c263131ff6c3d   3.5.0             2d19h
rendered-master-3b5d027f3a6e19c6c6321382a6f0ff73    035a7f3c16e820ed0461b25ba82c263131ff6c3d   3.5.0             10d
rendered-master-531d972ec9c5be2cb0df6e29ea74b761    035a7f3c16e820ed0461b25ba82c263131ff6c3d   3.5.0             7d3h
rendered-worker-3c8750c881df6f82403924904fac6469    035a7f3c16e820ed0461b25ba82c263131ff6c3d   3.5.0             2d19h
rendered-worker-d634f7e297ea4aeb892ca8279b049985    035a7f3c16e820ed0461b25ba82c263131ff6c3d   3.5.0             8d
rendered-worker-d93ebcbc2d78faaf1b91419d22f75387    035a7f3c16e820ed0461b25ba82c263131ff6c3d   3.5.0             7d3h
rendered-worker-d98bd75b78ad2605cb64e1bbd15eaf0c    035a7f3c16e820ed0461b25ba82c263131ff6c3d   3.5.0             10d
hsuma@plnx-admin:~/ocp-ai-config$ oc get mcp worker -w
NAME     CONFIG                                             UPDATED   UPDATING   DEGRADED   MACHINECOUNT   READYMACHINECOUNT   UPDATEDMACHINECOUNT   DEGRADEDMACHINECOUNT   AGE
worker   rendered-worker-3c8750c881df6f82403924904fac6469   True      False      True       2              2                   2                     0                      10d




apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-worker-nm-dns-fix
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.5.0
    storage:
      files:
        - path: /usr/local/bin/ensure-nm-dns.sh
          mode: 0755
          contents:
            inline: |
              #!/bin/bash
              # ensure-nm-dns.sh
              # Ensures /var/run/NetworkManager/resolv.conf has DNS servers
              # before kubelet starts. Fixes OVN-K bare-metal bug where
              # ovs-if-br-ex is created at runtime without DNS, causing
              # resolv-prepender.sh to hang indefinitely and kubelet to
              # fail with "NM resolv-prepender failed".
              #
              # Root cause: OVN-K creates ovs-if-br-ex in /run/NetworkManager/
              # system-connections/ (tmpfs, wiped on reboot) without ipv4.dns.
              # NM then generates resolv.conf with no nameservers.
              #
              # This runs as a oneshot before kubelet — no race condition.
              #
              # Cluster: ocp-ai.calix.local (OCP 4.20.13)
              # DNS: 10.172.248.31, 10.172.248.32
              # Author: Haj Suma
              # Date: February 26, 2026

              RESOLV="/var/run/NetworkManager/resolv.conf"
              DNS1="10.172.248.31"
              DNS2="10.172.248.32"
              SEARCH="calix.local"
              MAX_WAIT=120
              INTERVAL=2

              echo "[ensure-nm-dns] Waiting for ${RESOLV} to exist (max ${MAX_WAIT}s)..."

              elapsed=0
              while [ ! -f "$RESOLV" ]; do
                if [ $elapsed -ge $MAX_WAIT ]; then
                  echo "[ensure-nm-dns] WARN: ${RESOLV} not found after ${MAX_WAIT}s, creating it"
                  mkdir -p /var/run/NetworkManager
                  touch "$RESOLV"
                  break
                fi
                sleep $INTERVAL
                elapsed=$((elapsed + INTERVAL))
              done

              echo "[ensure-nm-dns] ${RESOLV} exists after ${elapsed}s"

              if grep -q "nameserver" "$RESOLV" 2>/dev/null; then
                echo "[ensure-nm-dns] DNS already present in ${RESOLV}, nothing to do"
                cat "$RESOLV"
                exit 0
              fi

              echo "[ensure-nm-dns] No nameservers found, injecting DNS..."
              printf "# Injected by ensure-nm-dns.sh (MachineConfig 99-worker-nm-dns-fix)\n# OVN-K does not inject DNS into ovs-if-br-ex on bare metal\nsearch %s\nnameserver %s\nnameserver %s\n" "$SEARCH" "$DNS1" "$DNS2" > "$RESOLV"

              if nmcli connection show ovs-if-br-ex &>/dev/null; then
                echo "[ensure-nm-dns] Injecting DNS into ovs-if-br-ex NM connection..."
                nmcli connection modify ovs-if-br-ex ipv4.dns "${DNS1} ${DNS2}" ipv4.dns-priority 40
                nmcli connection up ovs-if-br-ex 2>/dev/null || true
              fi

              echo "[ensure-nm-dns] DNS fix applied:"
              cat "$RESOLV"
              exit 0
    systemd:
      units:
        - name: ensure-nm-dns.service
          enabled: true
          contents: |
            [Unit]
            Description=Ensure NM resolv.conf has DNS servers (OVN-K bare-metal fix)
            After=NetworkManager.service
            Before=kubelet.service
            Before=nodeip-configuration.service

            [Service]
            Type=oneshot
            RemainAfterExit=yes
            ExecStart=/usr/local/bin/ensure-nm-dns.sh
            TimeoutStartSec=180

            [Install]
            WantedBy=multi-user.target
