apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: milvus
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: git@bitbucket.org:calixprod/ocp-ai-platform.git
    targetRevision: main
    path: milvus
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
