version: '3'

services:
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - /opt/registry/data:/var/lib/registry
      - /opt/registry/certs:/certs
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
    restart: always

  registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    container_name: registry-ui
    ports:
      - "8080:80"
    environment:
      - ENV_DOCKER_REGISTRY_HOST=plnx-ai-registry.calix.local
      - ENV_DOCKER_REGISTRY_PORT=5000
    depends_on:
      - registry
    restart: always

  nginx-ui-proxy:
    image: nginx:latest
    container_name: nginx-ui-proxy
    ports:
      - "443:443"
    volumes:
      - /opt/registry/certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - registry-ui
    restart: always


    events {}

http {
  server {
    listen 443 ssl;

    ssl_certificate /etc/nginx/certs/domain.crt;
    ssl_certificate_key /etc/nginx/certs/domain.key;

    location / {
      proxy_pass http://registry-ui:80;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
